// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Myd;

#nullable disable

namespace SCFHomework8.Migrations
{
    [DbContext(typeof(MyDB))]
    partial class MyDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ORDER.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ORDER_DATAIL.Node", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Order_DetailId")
                        .HasColumnType("int");

                    b.Property<int>("cost")
                        .HasColumnType("int");

                    b.Property<int>("num")
                        .HasColumnType("int");

                    b.HasKey("name");

                    b.HasIndex("Order_DetailId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("ORDER_DATAIL.Order_Datail", b =>
                {
                    b.Property<int>("Order_DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Order_DetailId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Order_Details");
                });

            modelBuilder.Entity("ORDER_DATAIL.Node", b =>
                {
                    b.HasOne("ORDER_DATAIL.Order_Datail", "Order_Detail")
                        .WithMany("Goods")
                        .HasForeignKey("Order_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order_Detail");
                });

            modelBuilder.Entity("ORDER_DATAIL.Order_Datail", b =>
                {
                    b.HasOne("ORDER.Order", "Order")
                        .WithOne("datail")
                        .HasForeignKey("ORDER_DATAIL.Order_Datail", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ORDER.Order", b =>
                {
                    b.Navigation("datail")
                        .IsRequired();
                });

            modelBuilder.Entity("ORDER_DATAIL.Order_Datail", b =>
                {
                    b.Navigation("Goods");
                });
#pragma warning restore 612, 618
        }
    }
}
